### ISSUE TITLE
TRIAL REGISTRATION NUMBER is tagged as BACKGROUND

### ISSUE THREAD

**Issue by Yasu00** [Franck-Dernoncourt/pubmed-rct#1]
I found many tagging errors: mainly "TRIAL REGISTRATION NUMBER" is tagged as "BACKGROUND"
Here is a comparison of the case of ###25428632

- https://www.ncbi.nlm.nih.gov/pubmed/25428632
![pubmed_paper](https://user-images.githubusercontent.com/23566998/37505768-dade3a52-2929-11e8-8927-94ad1a942647.png)

- RCT dataset ###25428632
![rct_dataset](https://user-images.githubusercontent.com/23566998/37505758-c04e014a-2929-11e8-97c4-5ad292a3b24b.png)
In this case, ETHICS AND DISSEMINATION is also tagged as BACKGROUND

**Comment by Franck-Dernoncourt** [comment]
That's correct. That's how PubMed labeled these sentences. I guess one can view them as administrative background.

From the [paper](https://arxiv.org/pdf/1710.06071v1.pdf), section 3.1:

> The label of each section was originally given by the authors of the articles, typically following the guidelines given by journals: as many labels exist, PubMed maps them into a smaller set of standardized labels: background, objective, methods, results, conclusions, “None”, “Unassigned”, or “” (empty string).
