### ISSUE TITLE
Untokenised version of the dataset

### ISSUE THREAD

**Issue by DeNeutoy** [Franck-Dernoncourt/pubmed-rct#2]
Hi @Franck-Dernoncourt - great dataset!

Is there an untokenised version of the dataset available?

Thanks!

Mark

**Comment by Franck-Dernoncourt** [comment]
Hi Mark, 

Thanks for the interest in our corpus. Unfortunately I couldn't find an untokenised version of the dataset available (that wasn't clever of me at all...). I looked at my disks and found an untokenised version of the same abstracts, but it might be a bit difficult to link it back to the PubMed 200k RCT dataset. I believe it would need a bit of string matching to infer which untokenised abstract corresponds to which PubMed 200k RCT abstract.

Here is the untokenised version of the same abstracts (remove the trailing 4 characters `.zip` of each filename before unzipping, I had to add it to go around some GitHub imitations):

- [structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.001.zip](https://github.com/Franck-Dernoncourt/pubmed-rct/files/3723291/structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.001.zip) 
- [structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.002.zip](https://github.com/Franck-Dernoncourt/pubmed-rct/files/3723302/structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.002.zip)
- [structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.003.zip](https://github.com/Franck-Dernoncourt/pubmed-rct/files/3723303/structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.003.zip)
- [structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.004.zip](https://github.com/Franck-Dernoncourt/pubmed-rct/files/3723304/structured_abstracts_train190654_valid2500_test2500_case_sensitive.zip.004.zip)

**Comment by DeNeutoy** [comment]
Ok, no problem. Thanks!
