### ISSUE TITLE
Full-text versions of these papers?

### ISSUE THREAD

**Issue by MSheshera** [Franck-Dernoncourt/pubmed-rct#3]
Are there versions of this dataset with the full text of it available? Are you aware of work of this kind? If not, is it possible to query for them and build it up? What would be your recommendations for building up full text of the articles, if any?

**Comment by Franck-Dernoncourt** [comment]
I don't have such a version. Unfortunately most randomized controlled
trials are behind paywalls. For the randomized controlled trials that
aren't behind paywall, you can retrieve their full text using their pubmed
ID (the one we provide in this dataset for each paper) via PMC or pubmed
API/dump from what I recall.

**Comment by MSheshera** [comment]
I see! Thank you for responding. Are the abstracts which are part of the dataset ones without a paywall? Or is likely a mix of both?

**Comment by Franck-Dernoncourt** [comment]
yes the abstracts can be accessed without a paywall.  See
https://www.aclweb.org/anthology/I17-2052.pdf   section 3

**Comment by MSheshera** [comment]
I see i see. And the full texts? Or is there no guarantee on availability of full texts for the papers which are part of the dataset?

**Comment by Franck-Dernoncourt** [comment]
There is unfortunately no guarantee on the availability of full texts for
the papers which are part of the dataset.

As mentioned in
https://dspace.mit.edu/bitstream/handle/1721.1/111880/1004959482-MIT.pdf:

>  Medical researchers must think about the implications of not making
research freely available when deciding to publish in pay-walled venues.

FYI [Why do tenured professors still publish in pay-walled venues?](
https://academia.stackexchange.com/q/51730/452)

**Comment by Franck-Dernoncourt** [comment]
There is unfortunately no guarantee on the availability of full texts for
the papers which are part of the dataset.

As mentioned in
https://dspace.mit.edu/bitstream/handle/1721.1/111880/1004959482-MIT.pdf:

>  Medical researchers must think about the implications of not making
research freely available when deciding to publish in pay-walled venues.

FYI [Why do tenured professors still publish in pay-walled venues?](https://academia.stackexchange.com/q/51730/452)

**Comment by MSheshera** [comment]
I see i see. Thank you for the clarifications and for the links to discussions! :)
